######################################################################
# Automatically generated by qmake (2.01a) dom dic 27 17:08:11 2020
######################################################################

TEMPLATE = app
TARGET = Indirizzario
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Contact.h MainFrame.h NContact.h
SOURCES += application.cpp Contact.cpp MainFrame.cpp NContact.cpp
