######################################################################
# Automatically generated by qmake (2.01a) dom mar 17 12:49:43 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += esercizio11.h
SOURCES += esercizio11.cpp main.cpp
