######################################################################
# Automatically generated by qmake (2.01a) dom mar 17 12:36:57 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += esercizio8.cpp
