######################################################################
# Automatically generated by qmake (2.01a) ven giu 4 00:41:00 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += esercizio28.h
SOURCES += esercizio28.cpp main.cpp
