######################################################################
# Automatically generated by qmake (2.01a) dom mar 17 12:14:26 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += esercizio4.cpp
