######################################################################
# Automatically generated by qmake (2.01a) mer giu 2 17:10:39 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += esercizio22.h
SOURCES += esercizio22.cpp main.cpp
