######################################################################
# Automatically generated by qmake (2.01a) dom mar 17 13:13:58 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += esercizio15.h
SOURCES += esercizio15.cpp main.cpp
