######################################################################
# Automatically generated by qmake (2.01a) dom mar 17 12:41:28 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += esercizio9.cpp
