######################################################################
# Automatically generated by qmake (2.01a) dom mar 17 13:08:00 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += esercizio14.h
SOURCES += esercizio14.cpp main.cpp
