######################################################################
# Automatically generated by qmake (2.01a) sab feb 20 15:54:41 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += graphicHelloWorld.cpp

QT += widgets

