######################################################################
# Automatically generated by qmake (2.01a) ven giu 4 00:31:08 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += esercizio26.h
SOURCES += esercizio26.cpp main.cpp
