######################################################################
# Automatically generated by qmake (2.01a) dom dic 20 17:01:56 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += esercizio29.h
SOURCES += esercizio29.cpp main.cpp
