######################################################################
# Automatically generated by qmake (2.01a) ven giu 4 00:26:17 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += esercizio25.cpp
