######################################################################
# Automatically generated by qmake (2.01a) gio ago 25 22:05:59 2016
######################################################################

TEMPLATE = app
TARGET = Indirizzario
DEPENDPATH += .
INCLUDEPATH += .
QT += sql

# Input
HEADERS += Contact.h MainFrame.h NContact.h
SOURCES += application.cpp Contact.cpp MainFrame.cpp NContact.cpp
