######################################################################
# Automatically generated by qmake (2.01a) mer giu 2 17:00:27 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += esercizio19.h
SOURCES += esercizio19.cpp main.cpp
