######################################################################
# Automatically generated by qmake (2.01a) dom mar 17 12:08:58 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += esercizio3.cpp
