######################################################################
# Automatically generated by qmake (2.01a) mer giu 2 17:07:25 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += esercizio21.h
SOURCES += esercizio21.cpp main.cpp
