######################################################################
# Automatically generated by qmake (2.01a) ven dic 18 01:45:55 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += esercizio30.h
SOURCES += esercizio30.cpp main.cpp
