######################################################################
# Automatically generated by qmake (2.01a) dom mar 17 12:58:21 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += esercizio13.h
SOURCES += esercizio13.cpp main.cpp
