######################################################################
# Automatically generated by qmake (3.0) dom giu 27 17:44:42 2021
######################################################################

TEMPLATE = app
TARGET = eventHandling
INCLUDEPATH += .

# Input
HEADERS += EventHandling.h
SOURCES += EventHandling.cpp main.cpp

QT += widgets
