######################################################################
# Automatically generated by qmake (2.01a) ven giu 4 00:23:53 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += esercizio24.cpp
