######################################################################
# Automatically generated by qmake (2.01a) gio gen 7 00:45:37 2021
######################################################################

TEMPLATE = app
TARGET = Indirizzario
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainFrame.h
SOURCES += application.cpp MainFrame.cpp
