######################################################################
# Automatically generated by qmake (2.01a) mer giu 2 17:03:21 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += esercizio20.h
SOURCES += esercizio20.cpp main.cpp
