######################################################################
# Automatically generated by qmake (2.01a) dom mar 17 12:46:03 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += esercizio10.cpp
