######################################################################
# Automatically generated by qmake (2.01a) mer giu 2 16:57:53 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += esercizio18.h
SOURCES += esercizio18.cpp main.cpp
