######################################################################
# Automatically generated by qmake (2.01a) dom mar 17 12:19:59 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += esercizio5.cpp
