######################################################################
# Automatically generated by qmake (2.01a) mer giu 2 16:54:17 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += esercizio17.h
SOURCES += esercizio17.cpp main.cpp
