######################################################################
# Automatically generated by qmake (2.01a) dom mag 21 17:56:30 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += esercizio2.cpp
