######################################################################
# Automatically generated by qmake (2.01a) dom mar 17 12:29:21 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += esercizio6.cpp
