######################################################################
# Automatically generated by qmake (2.01a) ven nov 6 22:40:22 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += esercizio1.cpp
