######################################################################
# Automatically generated by qmake (2.01a) dom mar 17 12:53:09 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += esercizio12.cpp
