######################################################################
# Automatically generated by qmake (2.01a) mer giu 2 16:49:00 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += esercizio16.h
SOURCES += esercizio16.cpp main.cpp
