######################################################################
# Automatically generated by qmake (2.01a) dom mar 17 12:33:56 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += esercizio7.cpp
