######################################################################
# Automatically generated by qmake (2.01a) ven giu 4 00:35:39 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += esercizio27.h
SOURCES += esercizio27.cpp main.cpp
