######################################################################
# Automatically generated by qmake (2.01a) ven giu 4 00:22:32 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += esercizio23.cpp
